//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShoes.Client.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string CONTAINER_ID {
            get {
                return ((string)(this["CONTAINER_ID"]));
            }
            set {
                this["CONTAINER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SHOES_JSON {
            get {
                return ((string)(this["SHOES_JSON"]));
            }
            set {
                this["SHOES_JSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://221.161.177.193:8080/api/qrcode/check?qrCode=")]
        public string QR_CALL_URL_DEBUG {
            get {
                return ((string)(this["QR_CALL_URL_DEBUG"]));
            }
            set {
                this["QR_CALL_URL_DEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.103:8554")]
        public string WEBVIEW_URL {
            get {
                return ((string)(this["WEBVIEW_URL"]));
            }
            set {
                this["WEBVIEW_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MAT_DATA_INSERT_URL {
            get {
                return ((string)(this["MAT_DATA_INSERT_URL"]));
            }
            set {
                this["MAT_DATA_INSERT_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://smartshoes.kr/api/qrcode/check?qrCode=")]
        public string QR_CALL_URL_RELEASE {
            get {
                return ((string)(this["QR_CALL_URL_RELEASE"]));
            }
            set {
                this["QR_CALL_URL_RELEASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6e400001-b5a3-f393-e0a9-e50e24dcca9e")]
        public string SERVICE_UUID {
            get {
                return ((string)(this["SERVICE_UUID"]));
            }
            set {
                this["SERVICE_UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6e400003-b5a3-f393-e0a9-e50e24dcca9e")]
        public string NOTIFY_UUID {
            get {
                return ((string)(this["NOTIFY_UUID"]));
            }
            set {
                this["NOTIFY_UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6e400002-b5a3-f393-e0a9-e50e24dcca9e")]
        public string WRITE_UUID {
            get {
                return ((string)(this["WRITE_UUID"]));
            }
            set {
                this["WRITE_UUID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SENSOR_SET_TIME {
            get {
                return ((int)(this["SENSOR_SET_TIME"]));
            }
            set {
                this["SENSOR_SET_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://221.161.177.194:8081/api/shoes/list?containerSid=")]
        public string SHOES_CALL_URL_DEBUG {
            get {
                return ((string)(this["SHOES_CALL_URL_DEBUG"]));
            }
            set {
                this["SHOES_CALL_URL_DEBUG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://221.161.177.194/api/shoes/list?containerSid=")]
        public string SHOES_CALL_URL_RELEASE {
            get {
                return ((string)(this["SHOES_CALL_URL_RELEASE"]));
            }
            set {
                this["SHOES_CALL_URL_RELEASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SELECT_LEFT_SHOE {
            get {
                return ((string)(this["SELECT_LEFT_SHOE"]));
            }
            set {
                this["SELECT_LEFT_SHOE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SELECT_RIGHT_SHOE {
            get {
                return ((string)(this["SELECT_RIGHT_SHOE"]));
            }
            set {
                this["SELECT_RIGHT_SHOE"] = value;
            }
        }
    }
}
